.travis.yml, skale/utils/account_tools.py, tests/constants.py, tests/contracts/manager_test.py, tests/utils/account_tools_test.py
Change ETH_TRANSFER_VALUE check logic
Refactor .travis.yml file
Remove pytest.mark.skip from manager_tests create_schain
**What**:
**Why**:
**How**:
**Checklist**:
-   [ ] Tests
=> Fix send_ether test (removed volatile wait_for=False condition testing)

.travis.yml, skale/contracts/manager.py, skale/contracts/token.py, skale/utils/constants.py, skale/utils/helper.py, tests/prepare_data.py
**What**:
**Why**:
**How**:
**Checklist**:
-   [ ] Tests
=> Make skale.py compitable with skale-manager, which uses ERC-777

skale/contracts/data/schains_data.py
**What**:
**Why**:
**How**:
**Checklist**:
-   [ ] Tests
=> Fix flake8 error

.gitignore, .travis.yml, CHANGELOG.md, CODEOWNERS, README.md, RELEASES.md, examples/nodes.py, examples/schains.py, setup.py, skale/contracts/constants.py, skale/contracts/contract_manager.py, skale/contracts/data/nodes_data.py, skale/contracts/data/schains_data.py, skale/contracts/manager.py, skale/main.py, skale/utils/account_tools.py, skale/utils/helper.py, skale/utils/web3_utils.py, tests/contracts/constants_test.py, tests/contracts/manager_test.py, tests/contracts/token_test.py, tests/helper_test.py, tests/main_test.py, tests/multithreading_test.py, tests/prepare_data.py, tests/utils/account_tools_test.py
**What**:
Move everything to `web3py` v5, split helper file, move all web3-related functionality, other changes to fully support `web3==5.2.2`.
**Checklist**:
-   [x] Documentation
-   [x] Tests
-   [x] Ready to be merged
This one is ready to be merged.  
This release contains breaking changes, containers using `skale.py` should be updated accordingly.
=> SKALE-1685 new web3py, new helpers, fix threads, update tests

setup.py, skale/manager_client.py, skale/utils/exceptions.py, skale/wallets/__init__.py, skale/wallets/ledger_wallet.py, skale/wallets/rpc_wallet.py, tests/wallets/ledger_test.py
optional wallet argument, wallet property, setter, and validation, add exception classes
=> SKALE-1778 Updated wallets functionality, fix ledger import error

skale/contracts/constants.py, skale/contracts/dkg.py, skale/contracts/manager.py, skale/contracts/token.py, skale/manager_client.py, skale/transactions/tools.py, skale/utils/web3_utils.py, tests/contracts/dkg_test.py
Also increase default blocks to wait for receipt to 5
=> Change gas price to average for all transaction except dkg related

setup.py
low risk
update `sgx.py` version to support latest changes
=> SKALE-2545 bump sgx.py version

skale/dataclasses/schain_node_info.py
=> SKALE-2810 write bls public key as str

skale/schain_config/generator.py
low risk
fix get bls public key from contract
=> SKALE-2810 fix generating config

setup.py
low risk
update sgx.py manager
=> SKALE-2835 update sgx.py version

setup.py
=> SKALE-3024 update sgx.py

skale/contracts/manager/key_storage.py, skale/schain_config/generator.py, tests/manager/key_storage_test.py, tests/schain_config/generator_test.py
low risk
remove unused function
=> SKALE-2892 remove depricated functions

skale/contracts/manager/token.py
=> SKALE-3239 Add mint function

skale/contracts/manager/dkg.py, tests/manager/dkg_test.py
add all dkg functions to skale.py
=> Enhancement/skale 3169 move all dkg functions to skale.py

setup.py, skale/wallets/ledger_wallet.py, skale/wallets/rpc_wallet.py, tests/wallets/rpc_test.py, tests/wallets/sgx_test.py
- Bump web3py version to 5.13.1
- Ticket SKALE-3005
=> Update web3py version (SKALE-3005)

skale/contracts/manager/manager.py, tests/manager/manager_test.py
=> SKALE-3798 Add delete_schain_by_root

skale/contracts/ima/linker.py
**What**:
**Why**:
**How**:
**Checklist**:
-   [ ] Tests
=> SKALE-4253 Pass mainnet contracts as list

.flake8, skale/utils/constants.py
**What**:
**Why**:
**How**:
**Checklist**:
-   [ ] Tests
=> SKALE-4369 Remove schain types dict

skale/dataclasses/node_info.py, skale/dataclasses/skaled_ports.py
**What**:
**Why**:
**How**:
**Checklist**:
-   [ ] Tests
=> SKALE-4837 Remove pg ports from skaled

.github/workflows/test.yml, pytest.ini, tests/rotation_history/rotation_history_test.py
**What**:
**Why**:
**How**:
**Checklist**:
-   [ ] Tests
=> SKALE-4837 Enable failed DKG RH test, update SM version

skale/schain_config/rotation_history.py
**What**:
**Why**:
**How**:
**Checklist**:
-   [ ] Tests
=> SKALE-4884 Fix rotation history for node_id=0

.github/workflows/test.yml, setup.py, skale/contracts/manager/manager.py, skale/contracts/manager/nodes.py, skale/contracts/manager/schains.py, skale/dataclasses/schain_options.py, skale/utils/contracts_provision/main.py, tests/manager/manager_test.py, tests/manager/schains_internal_test.py, tests/manager/schains_test.py, tests/rotation_history/utils.py
**What**:
**Why**:
**How**:
**Checklist**:
-   [ ] Tests
=> SKALE-4898 Add custom config options for sChain

skale/contracts/manager/node_rotation.py, tests/manager/node_rotation_test.py
**What**:
**Why**:
**How**:
**Checklist**:
-   [ ] Tests
=> SKALE-4942 Replace finish_ts with freeze_until

.github/workflows/test.yml, scripts/install_host_dependencies.sh, scripts/install_python_dependencies.sh, scripts/run_allocator_tests.sh, scripts/run_manager_tests.sh, setup.py, skale/contracts/manager/node_rotation.py, skale/schain_config/rotation_history.py, tests/conftest.py, tests/helper.py, tests/manager/base_contract_test.py, tests/manager/dkg_test.py, tests/manager/manager_test.py, tests/manager/node_rotation_test.py, tests/rotation_history/rotation_history_test.py, tests/transaction_tools_test.py, tests/utils/account_tools_test.py, tests/wallets/common_test.py, tests/wallets/ledger_test.py, tests/wallets/redis_adapter_test.py, tests/wallets/rpc_test.py, tests/wallets/sgx_test.py
Incorrect rotation history in schain config after failed DKG
=> Rotation history bug

.github/workflows/test.yml, .gitmodules, skale/transactions/tools.py, skale/utils/contracts_provision/main.py, tests/conftest.py, tests/main_test.py, tests/manager/delegation/delegation_controller_test.py, tests/manager/delegation/validator_service_test.py, tests/manager/manager_test.py, tests/manager/node_rotation_test.py, tests/manager/sync_manager_test.py, tests/utils/account_tools_test.py, tests/utils/web3_utils_test.py
Only CI/CD pipeline was changed. 
No performance changes was made.
=> Switch to hardhat node

CODEOWNERS, skale/contracts/manager/dkg.py, tests/rotation_history/rotation_history_test.py
Add additional dkg contract call wrapper.
No performance related changes.
=> Add is node broadcasted

setup.py
Fix eth-account by adding typing-extensions to setup.py
=> Add typing-extensions to setup.py

scripts/calculate_version.sh, setup.py
Changes:
1. Fix versioning.
2. Fix types package.
Testing:
- Tested by installing the package from github
Performance:
- No performance related changes were introduced.
=> Fix packaging
